# Generated by Django 4.2.26 on 2025-11-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_role_approved',
            field=models.BooleanField(default=True, help_text='Only approved roles unlock their special dashboards.'),
        ),
    ]
